# Generated by Django 5.2.7 on 2025-10-23 14:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('es_swing', models.BooleanField(default=False)),
                ('puntos', models.IntegerField(default=0)),
                ('speakers_total', models.IntegerField(default=0)),
                ('speakers_prom', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Ronda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('emparejada', models.BooleanField(default=False)),
                ('cerrada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('responsable', models.CharField(max_length=120)),
                ('n_equipos', models.PositiveIntegerField()),
                ('n_clasificados', models.PositiveIntegerField()),
                ('n_rondas', models.PositiveIntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='CONFIG', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Debatiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debatientes', to='tabla.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ronda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='tabla.ronda')),
            ],
        ),
        migrations.CreateModel(
            name='SalaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(choices=[('OG', 'OG'), ('OO', 'OO'), ('CG', 'CG'), ('CO', 'CO')], max_length=2)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='tabla.equipo')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='tabla.sala')),
            ],
            options={
                'unique_together': {('sala', 'posicion')},
            },
        ),
        migrations.CreateModel(
            name='ResultadoSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('puntos', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('orador1', models.IntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)])),
                ('orador2', models.IntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)])),
                ('sala_equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='tabla.salaequipo')),
            ],
        ),
        migrations.AddField(
            model_name='ronda',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rondas', to='tabla.torneo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='tabla.torneo'),
        ),
        migrations.AlterUniqueTogether(
            name='ronda',
            unique_together={('torneo', 'numero')},
        ),
        migrations.CreateModel(
            name='Enfrentamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enf_a', to='tabla.equipo')),
                ('equipo_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enf_b', to='tabla.equipo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfrentamientos', to='tabla.torneo')),
            ],
            options={
                'unique_together': {('torneo', 'equipo_a', 'equipo_b')},
            },
        ),
    ]
