# Generated by Django 5.2.7 on 2025-10-23 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabla', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ronda',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='torneo',
            name='estado',
        ),
        migrations.AddField(
            model_name='torneo',
            name='cerrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='torneo',
            name='ganador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torneos_ganados', to='tabla.equipo'),
        ),
        migrations.AlterField(
            model_name='resultadosala',
            name='orador1',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='resultadosala',
            name='orador2',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='resultadosala',
            name='puntos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resultadosala',
            name='ranking',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sala',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='salaequipo',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabla.equipo'),
        ),
        migrations.AlterField(
            model_name='salaequipo',
            name='posicion',
            field=models.CharField(max_length=2),
        ),
        migrations.DeleteModel(
            name='Enfrentamiento',
        ),
    ]
