# Generated by Django 5.2.3 on 2025-12-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabla', '0002_alter_ronda_unique_together_remove_torneo_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='lugar_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='torneo',
            name='lugar_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='torneo',
            name='lugar_nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
